plugins:
  email_topic_generation_enabled:
    default: true
    client: true
  email_topic_generation_button_title:
    client: true
    default: "staff email generation"
  email_topic_generation_button_label:
    default: "Staff Email"
    client: true
  email_topic_generation_popup_background_image_link:
    default: ""
    client: true
